### PR TITLE
Fix memory leaks and appserver crashes related to #2

### PR DESCRIPTION
**Pull request by janus2**

### CODE REVIEW

**Comment by pulkomandy** [comment]
Shouldn't dragmsg be allocated on the stack instead?

**Comment by janus2** [comment]
Totally!

**Comment by janus2** [comment]
I think it could be awesome to add a text_run_array to the drag message, not sure on the font size. What do you think?

**Comment by janus2** [comment]
In the old settings there are many errors and inconsistencies. I made some changes:
- Remove splashscreen  (Applications use splashscreen to cheat on loading time, FontBoy is super fast)
- Use always the live update, now the revert button works with the live update as expected
- Use a global default button for the user options
- Replace the BOutlineView with a BTabView
- Colors selection use the same interface of Appearance (support for drag and drop) ColorButton had different bugs
- Layout
- Other bug fix

**Comment by janus2** [comment]
Fix #7 and #8.

**Pull request merged**
