### PR TITLE
FontBoy: get initial window height and horizontal scrollbar right

### LINKED ISSUE #18: Black space on bottom
I haven't resized or changed any setting . If you notice there is some blank space at the bottom of the page that could be removed .
fnnt

### PR DESCRIPTION
**Pull request by owenca**
Fixes #18 and #29

### CODE REVIEW

**Comment by humdingerb** [comment]
I didn't see an obvious issue with the window before this change. But with these changes, after removing the FontBoy_prefs, I get a very tall window that's higher than the screen and can't be vertically resized...

**Comment by owenca** [comment]
Here is the "After" screenshot, with ~/config/settings/Frontboy_prefs removed first:

screen shot 2018-01-01 at 12 12 10 am

**Comment by owenca** [comment]
The "Before" screenshot is [here](https://github.com/HaikuArchives/FontBoy/issues/29).

**Comment by humdingerb** [comment]
I have over 200 ttf fonts (most different styles of a font family). This is the window height I got with `hey FontBoy get Frame of Window 0`:  5123.
That's too high. :)

**Comment by owenca** [comment]
I see. How many rows did you have? I need to limit the number of rows or do something about it.

**Comment by janus2** [comment]
I have a huge tall window and the space at the bottom is still there. 4 columns with one with 4 elements.
You can't use the rows as a measure because the user can change the font size in the settings and I haven't check the code but I am pretty sure the system menu font size matter.

**Comment by owenca** [comment]
If you are talking about the menu bar, then it's accounted for. The issue is probably related to the number of rows being calculated twice by the ListView and/or its base class. Will dig more into this later. Closing it for now...

**Comment by janus2** [comment]
Yes I'am talking about the menu bar and it is a problem...
## Menu 12pt
menu12pt
## Menu 24pt
menu24pt

**Comment by owenca** [comment]
What you saw is the symptom, not the cause. ;) Like I said, the height of the menu bar was accounted for.

**Comment by janus2** [comment]
Do you mean in ListWindow.cpp:49
`fontframe.top = menu_bar->Bounds().bottom +1.0;`

**Pull request closed without merging**
